[package]
name = "barcode_generator_code_39"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bmp = "0.5.0"
inquire = "0.6.2"
lazy_static = "1.4.0"
